version: '3.8'

networks:
  nginx-proxy:
    name: iot-net
    external: true

services:
  nadadores-uni:
    container_name: nadadores-uni
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=dev.nadadoresuni.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dev.nadadoresuni.com
      - LETSENCRYPT_EMAIL=jcanahuirev@gmail.com
      - NODE_ENV=production
    env_file:
      - ./.env
    networks:
      - nginx-proxy
